# Generated by Django 5.1.6 on 2026-04-21 10:10

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Video Title')),
                ('description', tinymce.models.HTMLField(verbose_name='Video Description & Transcript')),
                ('video_url', models.URLField(verbose_name='Video URL (YouTube, Vimeo, etc.)')),
                ('thumbnail', models.ImageField(upload_to='videos/thumbnails/', verbose_name='Custom Thumbnail')),
                ('category', models.CharField(choices=[('educational', 'Educational'), ('interview', 'Interview'), ('webinar', 'Webinar'), ('keynote', 'Keynote'), ('documentary', 'Documentary'), ('advocacy', 'Advocacy & Action'), ('panel', 'Panel Discussion'), ('tutorial', 'Tutorial'), ('announcement', 'Announcement')], default='educational', max_length=20)),
                ('speakers', models.CharField(max_length=500, verbose_name='Speakers/Presenters (comma-separated)')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (minutes)')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags (comma-separated)')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured Video')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
