"""
Django settings for aiel project.

Generated by 'django-admin startproject' using Django 3.2.25.
Compatible with Django 3.2+ (and Django 5.x if you upgrade).
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# ------------------------------------------------------------------------------
# Core paths
# ------------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------------------
# Environment
# ------------------------------------------------------------------------------
DJANGO_ENV = os.environ.get("DJANGO_ENV", "dev").lower()  # 'prod' on the server
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() == "true"

# SECURITY: set this in your environment
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "CHANGE-ME-IN-ENV")

# ------------------------------------------------------------------------------
# Hosts / CORS / CSRF
# ------------------------------------------------------------------------------
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "aielinstitute.org",
    "www.aielinstitute.org",
    "backend.aielinstitute.org",
    "191.101.1.79",
]

INSTALLED_APPS = [
    # third-party first so middleware can reference it
    "corsheaders",

    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # APIs / Editors
    "rest_framework",
    "tinymce",

    # Your apps
    "team",
    "events",
    "research",
    "board",
    "briefs",
    "community",
    "resources",
    "contactapi",
    "mediaapi",
    "subscription",
    "casestudy",
    "legalcommentary",
    "newsletter",
    "multimediaresource",
    "researchhighlight",
    "guides",
    "photos",
    "podcasts",
    "videos",
    "cms",
]

# Use BigAutoField for all models (Django 3.2+ default)
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MIDDLEWARE = [
    # CORS must be high in the list
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Frontends allowed to call your API
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://aielinstitute.org",
    "https://www.aielinstitute.org",
    "https://backend.aielinstitute.org",
]
CORS_ALLOW_CREDENTIALS = True

# CSRF (must include scheme + host; ports okay)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://aielinstitute.org",
    "https://www.aielinstitute.org",
    "https://backend.aielinstitute.org",
    "http://191.101.1.79",
    "http://191.101.1.79:8000",
]

ROOT_URLCONF = "aiel.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "aiel.wsgi.application"

# ------------------------------------------------------------------------------
# Database (SQLite locally; Postgres on prod with SSL)
# ------------------------------------------------------------------------------
if DJANGO_ENV == "prod":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "postgres"),
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST", "aiel-main-database.ctwgckq4ajwt.us-east-2.rds.amazonaws.com"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "OPTIONS": {
                "sslmode": os.environ.get("POSTGRES_SSLMODE", "require"),
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# ------------------------------------------------------------------------------
# REST Framework Configuration
# - AllowAny as default (public API), specific viewsets override as needed
# - Individual viewsets use IsAuthenticatedOrReadOnly for content
# - Authentication classes support both session and basic auth
# - Throttling prevents abuse of anonymous endpoints
# ------------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",  # Default is public; viewsets override as needed
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",  # Allow reasonable traffic for public endpoints
        "user": "1000/hour",
    },
}

# ------------------------------------------------------------------------------
# Password validation
# ------------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ------------------------------------------------------------------------------
# I18N / TZ
# ------------------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "UTC")  # set to "America/Edmonton" if you prefer
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ------------------------------------------------------------------------------
# Static & Media
# ------------------------------------------------------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ------------------------------------------------------------------------------
# Email (use env; example shows Gmail SMTP)
# ------------------------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() == "true"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# Contact form destination
CONTACT_US_EMAIL = os.environ.get("CONTACT_US_EMAIL", "info@aielinstitute.org")

# ------------------------------------------------------------------------------
# TinyMCE
# ------------------------------------------------------------------------------
TINYMCE_DEFAULT_CONFIG = {
    "cleanup_on_startup": True,
    "custom_undo_redo_levels": 20,
    "selector": "textarea",
    "theme": "silver",
    "plugins": """
        textcolor save link image media preview codesample contextmenu
        table code lists fullscreen insertdatetime nonbreaking
        contextmenu directionality searchreplace wordcount visualblocks
        visualchars code fullscreen autolink lists charmap print hr
        anchor pagebreak
    """,
    "toolbar1": """
        fullscreen preview bold italic underline | fontselect fontsizeselect |
        forecolor backcolor | alignleft alignright | aligncenter alignjustify |
        indent outdent | bullist numlist table | link image media | codesample
    """,
    "toolbar2": """
        visualblocks visualchars | charmap hr pagebreak nonbreaking anchor | code
    """,
    "contextmenu": "formats | link image",
    "menubar": True,
    "statusbar": True,
    "images_upload_url": "static/images/images",
    "images_upload_handler": "tinymce_image_upload_handler",
}
TINYMCE_EXTRA_MEDIA = {
    "css": {"all": []},
    "js": [
        "https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js",
        "admin/js/tinymce-upload.js",
    ],
}

# ------------------------------------------------------------------------------
# Security (auto-tighten when DEBUG=False)
# ------------------------------------------------------------------------------
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "63072000"))  # 2 years
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")  # if behind nginx/proxy

# ------------------------------------------------------------------------------
# Logging (simple baseline)
# ------------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {"handlers": ["console"], "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO")},
}
