# Generated by Django 5.1.6 on 2026-04-21 10:10

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Guide/Toolkit Title')),
                ('content', tinymce.models.HTMLField()),
                ('guide_type', models.CharField(choices=[('guide', 'Guide'), ('toolkit', 'Toolkit'), ('template', 'Template')], default='guide', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='guides_docs/', verbose_name='Document (PDF)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='guides_images/', verbose_name='Image')),
                ('year', models.PositiveIntegerField(verbose_name='Year of Publication')),
                ('authors', models.TextField(verbose_name='Authors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guide & Toolkit',
                'verbose_name_plural': 'Guides & Toolkits',
                'ordering': ['-created_at'],
            },
        ),
    ]
