# Generated by Django 5.1.6 on 2026-04-21 10:10

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Episode Title')),
                ('show_name', models.CharField(default='AIEL Podcast', max_length=255, verbose_name='Podcast Show Name')),
                ('description', tinymce.models.HTMLField(verbose_name='Episode Description & Show Notes')),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Episode Number')),
                ('season', models.PositiveIntegerField(default=1, verbose_name='Season')),
                ('host', models.CharField(max_length=255, verbose_name='Host/Narrator')),
                ('guest_speakers', models.TextField(blank=True, verbose_name='Guest Speakers (comma-separated)')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='podcasts/audio/', verbose_name='Audio File (MP3/WAV)')),
                ('episode_url', models.URLField(blank=True, verbose_name='Episode URL (Spotify, Apple Podcasts, etc.)')),
                ('transcript', tinymce.models.HTMLField(blank=True, verbose_name='Episode Transcript')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (minutes)')),
                ('thumbnail', models.ImageField(upload_to='podcasts/thumbnails/', verbose_name='Album Art/Thumbnail')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags (comma-separated)')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Podcast Episode',
                'verbose_name_plural': 'Podcast Episodes',
                'ordering': ['-season', '-episode_number', '-created_at'],
            },
        ),
    ]
