# Generated by Django 5.1.6 on 2026-04-21 10:10

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Gallery Title')),
                ('description', tinymce.models.HTMLField(verbose_name='Gallery Description')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Photo Gallery',
                'verbose_name_plural': 'Photo Galleries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Photo Title')),
                ('caption', tinymce.models.HTMLField(verbose_name='Photo Caption & Description')),
                ('photographer', models.CharField(max_length=255, verbose_name='Photographer')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('category', models.CharField(choices=[('event', 'Event Coverage'), ('landscape', 'Landscape'), ('portrait', 'Portrait'), ('documentary', 'Documentary'), ('advocacy', 'Advocacy & Action'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('community', 'Community')], default='documentary', max_length=20)),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Photo Image')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags (comma-separated)')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='photos.photogallery')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
